/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_marcos_ortega_jni_AppNativo */

#ifndef _Included_demo_marcos_ortega_jni_AppNativo
#define _Included_demo_marcos_ortega_jni_AppNativo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_marcos_ortega_jni_AppNativo
 * Method:    nativeInicializar
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_demo_marcos_ortega_jni_AppNativo_nativeInicializar
  (JNIEnv *, jobject, jobject);

/*
 * Class:     demo_marcos_ortega_jni_AppNativo
 * Method:    nativeDameContenidoAsset
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demo_marcos_ortega_jni_AppNativo_nativeDameContenidoAsset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     demo_marcos_ortega_jni_AppNativo
 * Method:    nativeFinalizar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_marcos_ortega_jni_AppNativo_nativeFinalizar
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
